version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:8089"
    volumes:
      - ./app:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - db  
    restart: on-failure

  db:
    image: mysql:8.0      
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: #define volumes