version: '3.9'
services:
  web:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - .:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST} 
      MYSQL_PORT: ${MYSQL_PORT} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #depends_on:
    #  - db  
    restart: on-failure
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8089"

  #db:
  #  image: mysql:8.0      
    #ports:
    #  - "3306:3030"      
  #  environment:
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #    MYSQL_DATABASE: ${MYSQL_DB}
  #    MYSQL_USER: ${MYSQL_USER}
  #    MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
  #  volumes:
  #    - db_data:/var/lib/mysql
  #  restart: always

#volumes:
#  db_data: #define volumes